[
    {
        "object": "Field18",
        "program": "shadow",
        "expType": "object",
        "note": "None",
        "comment": "2025B-589422, Virgo pointings",
        "wait": "False",
        "proposer": "Sand, David",
        "propid": "2025B-589422",
        "filter": "g",
        "exptime": 90,
        "RA": 188.7788,
        "dec": 6.8992
    },
    {
        "object": "Field8",
        "program": "shadow",
        "expType": "object",
        "note": "None",
        "comment": "2025B-589422, Virgo pointings",
        "wait": "False",
        "proposer": "Sand, David",
        "propid": "2025B-589422",
        "filter": "g",
        "exptime": 90,
        "RA": 187.6007,
        "dec": 8.4389
    },
    {
        "object": "Field20",
        "program": "shadow",
        "expType": "object",
        "note": "None",
        "comment": "2025B-589422, Virgo pointings",
        "wait": "False",
        "proposer": "Sand, David",
        "propid": "2025B-589422",
        "filter": "g",
        "exptime": 90,
        "RA": 185.6507,
        "dec": 8.9489
    },
    {
        "object": "Field9",
        "program": "shadow",
        "expType": "object",
        "note": "None",
        "comment": "2025B-589422, Virgo pointings",
        "wait": "False",
        "proposer": "Sand, David",
        "propid": "2025B-589422",
        "filter": "g",
        "exptime": 90,
        "RA": 186.0131,
        "dec": 7.1655
    },
    {
        "object": "Field10",
        "program": "shadow",
        "expType": "object",
        "note": "None",
        "comment": "2025B-589422, Virgo pointings",
        "wait": "False",
        "proposer": "Sand, David",
        "propid": "2025B-589422",
        "filter": "g",
        "exptime": 90,
        "RA": 184.8111,
        "dec": 5.7578
    },
    {
        "object": "Field1",
        "program": "shadow",
        "expType": "object",
        "note": "None",
        "comment": "2025B-589422, Virgo pointings",
        "wait": "False",
        "proposer": "Sand, David",
        "propid": "2025B-589422",
        "filter": "g",
        "exptime": 90,
        "RA": 187.7014,
        "dec": 12.3963
    }
]
